<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ImageMapper.Services</RootNamespace>
    <PackageId>tjmoore.ImageMapper.Services</PackageId>
    <Version>0.1.0</Version>
    <Authors>Tim Moore</Authors>
    <Product>ImageMapper</Product>
    <Description>Library of .NET services to extract metadata from images and provide data to front end consumers</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>   
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright (c) 2026 Tim Moore</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
    
  <ItemGroup>
    <PackageReference Include="MetadataExtractor" Version="2.9.3" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>  

  <ItemGroup>
    <InternalsVisibleTo Include="ImageMapper.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>
    
</Project>