# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x

    # On building, clear the NuGet cache, create a directory for the NuGet packages, and build the projects in the solution in the specified order
    # to ensure that package dependencies are built before restoring the next project.
    - name: Build
      run: |
        dotnet nuget locals all --clear
        mkdir nupkg
        dotnet build src/ImageMapper.Services
        dotnet build src/ImageMapper.RazorLib
        dotnet build src/ImageMapper.Web
        dotnet build src/ImageMapper.AppHost

    - name: Install SSL Certificates
      run: |
        dotnet dev-certs https --clean
        dotnet dev-certs https --trust
      env:
        SSL_CERT_DIR: '$HOME/.aspnet/dev-certs/trust:/usr/lib/ssl/certs'
      continue-on-error: true

    - name: Test
      run: dotnet test --verbosity normal
