name: Create packages on release
permissions:
  contents: read
  packages: write

on:
  release:
    types: [created]

jobs:
  create-package:
    name: Create NuGet package

    runs-on: ubuntu-latest

    env:
      NuGetFolder: ${{ github.workspace }}/nuget

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.7.0
        with:
          versionSpec: '6.8.x'

      - name: Determine Version
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v4.7.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Pack
        run: |
          dotnet pack src/ImageMapper.Services --configuration Release --output ${{ env.NuGetFolder }} /p:PackageVersion=${{ steps.version_step.outputs.fullSemVer }} -bl:imagemapper.services.binlog
          dotnet pack src/ImageMapper.RazorLib --configuration Release --output ${{ env.NuGetFolder }} /p:PackageVersion=${{ steps.version_step.outputs.fullSemVer }} -bl:imagemapper.razorlib.binlog

#      - name: Publish
#        run: |
#          dotnet nuget push ${{ env.NuGetFolder }}/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Upload binlogs
        uses: actions/upload-artifact@v7
        with:
          name: binlogs
          path: *.binlog

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v7
        with:
          name: nuget-packages
          path: ${{ env.NuGetFolder }}/*.nupkg

